### ISSUE TITLE
removeFromRunLoop:forMode: only defined for abstract class. Define -[NXOAuth2PostBodyStream removeFromRunLoop:forMode:]

### ISSUE THREAD

**Issue by mselevan** [nxtbgthng/OAuth2Client#129] opened 2014-08-27 04:26 UTC
Getting this crash. Not sure how to reproduce it yet, but anyone have any thoughts?

**Comment by Muesly** [comment] 2014-09-03 12:50
I get this too, but just on iOS 8

**Comment by dwa012** [comment] 2014-09-10 21:08
I am getting the same issue as well.

This is a pretty major bug at the moment.

**Comment by dwa012** [comment] 2014-09-10 21:23
My guess is that the problem is that the super implementation is guarded now.

https://github.com/nxtbgthng/OAuth2Client/blob/afae991569be76aef290bebfc9904ee81b8f1ba3/Sources/OAuth2Client/NXOAuth2PostBodyStream.m#L197

Here there is a super call which is what the XCode error seems to imply that super is no longer an option.

**Comment by dwa012** [comment] 2014-09-10 21:50
I fixed the issue in a fork of mine https://github.com/dwa012/OAuth2Client

Will make a pull request today

**Comment by Muesly** [comment] 2014-09-11 09:20
I'm not sure I understand fully, but will look forward to seeing your fix :)

**Comment by stigi** [comment] 2014-09-11 15:36
Has been merged with #135 and is now available in `develop`

**Comment by stigi** [comment] 2014-09-11 15:40
Also just made this available as version `1.2.7` via cocoapods. Thanks guys!

**Closed as completed by stigi** 2014-09-11 15:40 UTC

**Comment by eduardosasso** [comment] 2014-12-04 00:35
Do you guys know how to reproduce this? Your solution fixes the problem but I'm very intrigued to figure it out the specific scenario when it happens.

In our app we had two occurrences of this issue that affected hundreds of users. The weird thing is that we had this problem for the first time on Nov 25 and then Dec 2 and in both situations the error went away after a couple hours like magic. The Crashlytics screenshot shows the spikes.

![screen shot 2014-12-03 at 4 29 24 pm](https://cloud.githubusercontent.com/assets/65739/5291629/55feee74-7b0a-11e4-8207-120ed54357ac.png)

Any tips on how to track this down would be great.
