### ISSUE TITLE
[iOS] Cannot run on the selected destination

### ISSUE THREAD

**Issue by paularmstrong** [nxtbgthng/OAuth2Client#49] opened 2012-10-18 23:47 UTC
Following the steps for setting up an iOS application, I'm getting the following error upon build:

> The selected destination does not support the architecture for which the selected software is built.  Switch to a destination that supports that architecture in order to run the selected software.

More information:
- Deployment Target 5.0+ (tried 5.1 and 6.0 as well)
- Devices iPhone
- Build phases 

![build phases](http://dl.dropbox.com/u/4556236/Screenshots/8yli.png)
- Header Search Paths `$(SRCROOT)/lib/OAuth2Client` (recursive) (cloned as a git submodule to `./lib/OAuth2Client`)

**Comment by stigi** [comment] 2012-10-19 08:53
The problem is probably that the old `master` branch didn't support armv7s. I just created a new release (version `1.2.0`) with the latest changes from the `develop` branch that should solve this issue.

I'm closing the issue for now. Please reopen if the problem still exists.

**Closed as completed by stigi** 2012-10-19 08:53 UTC
